### ISSUE TITLE
The browser version doesn't work

### ISSUE THREAD

**Issue by Nowhk** [synesenom/ran#15]
the link you have in your main page (i.e. minified version) is broken https://raw.githubusercontent.com/synesenom/ran/master/ran.min.js

**Comment by synesenom** [comment]
Hi,

Thanks for the bug report! I updated the link to the browser version (there was a CORS issue with links to raw github files, now linking to unpkg). Also, note that the module is exported under 'ranjs' (also specified in the readme now). Here is a working jsfiddle:

https://jsfiddle.net/7mw8sf0o/1/

I hope it helps!

Cheers,
Enys

**Comment by synesenom** [comment]
I just checked your jsfiddle and saw you used

`ranjs.core.seed(0)`

Please note that this only sets the seed for the core functions. To set the seed for a distribution generator, use the generator's own method:

```javascript
let myDist = new ranjs.dist.Uniform(0, 1)
myDist.seed(0)
let samples = myDist.sample(1000)
```

Cheers,
Enys

**Comment by Nowhk** [comment]
Awesome! Thanks dude!
